Allow to pass custom handlers and key to traverse.children
bem-contrib/md-to-bemjson pull request #13
Opened 2018-06-27 17:12 UTC by zxqfox

2018-06-27 21:27 UTC, birhoff commented on packages/mdast-util-to-bemjson/lib/traverse.js
> +    const handler = userHandler ? userHandler.bind({ __base: baseHandler }) : baseHandler;
inherit костыль?

2018-06-27 21:28 UTC, birhoff commented on packages/mdast-util-to-bemjson/test/options.test.js
> +            console.log(bjson);
remove

2018-06-27 21:31 UTC, birhoff commented on packages/mdast-util-to-bemjson/lib/traverse.js
> +    const nodes = parent['children' || key] || [];
maybe you want
```
const nodes = parent['children'] || [].concat(parent[key])  || [];
```
we should check that nodes are array

2018-06-27 21:33 UTC, birhoff requested changes
few things

2018-06-28 16:15 UTC, zxqfox commented on packages/mdast-util-to-bemjson/lib/traverse.js
> +    const handler = userHandler ? userHandler.bind({ __base: baseHandler }) : baseHandler;
возможность фолбечиться на базовыы

2018-06-29 19:07 UTC, birhoff approved these changes

2018-06-29 21:00 UTC, merged